name: 🚀 Feature request
description: Suggest a feature for improving SSX
title: "[FEATURE] <title>"
labels: [Feature Request, Enhancement]
body:
- type: textarea
  attributes:
    label: Feature
    description: Describe the feature.
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Provide any additional details about the feature.
  validations:
    required: false
- type: textarea
  attributes:
    label: User Story
    description: Provide any user story that would help the team to understand the feature better.
  validations:
    required: false
